<<<<<<< HEAD
language: python
<<<<<<< HEAD
=======
Language: python
>>>>>>> ft-user-authentication-#160801485
=======
>>>>>>> ft-create-api-end-points-#160232316

python:
  - "3.7"

<<<<<<< HEAD

before_install :
  - pip install requirements.txt
  - pip install --user codecov
  
  
=======
>>>>>>> ft-create-api-end-points-#160232316
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

<<<<<<< HEAD
script:
  - pytest --cov-config .coveragerc test_app.py --pep8 test_app.py --cov-report term-missing

<<<<<<< HEAD
after_script:
  - coverage xml
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" && "$TRAVIS_PYTHON_VERSION" == "3.7" ]]; then ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT; fi
=======
script: python test_app.py
>>>>>>> ft-user-authentication-#160801485

after_success:
  - coveralls
  - CODECOV_TOKEN="81285440-a3ba-4193-8690-ac91298b2fb5"
<<<<<<< HEAD
=======

>>>>>>> ft-user-authentication-#160801485
=======
install:
  - pip install -r requirements.txt

script:
  - pytest --cov-config .coveragerc tests.py --pep8 test_app.py --cov-report term-missing

after_script:
  - coverage xml
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" && "$TRAVIS_PYTHON_VERSION" == "3.7" ]]; then ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT; fi

after_success:
  - coveralls
>>>>>>> ft-create-api-end-points-#160232316
