language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt
script:
  - coverage run --source=app -m pytest && coverage report

after_script:
  - coverage xml

after_success:
  - coveralls
