language: python

python:
  - "3.7"

install:
  - pip install -r requirements.txt
  - pip install --user codecov
  

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - python test_app.py

after_script:
  - coverage xml
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" && "$TRAVIS_PYTHON_VERSION" == "3.7" ]]; then ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT; fi

after_success:
  - coveralls
  - CODECOV_TOKEN="81285440-a3ba-4193-8690-ac91298b2fb5"







